# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 40, 141, 41))
        self.label.setObjectName("label")
        self.PlainText = QtWidgets.QLabel(self.centralwidget)
        self.PlainText.setGeometry(QtCore.QRect(160, 90, 81, 21))
        self.PlainText.setObjectName("PlainText")
        self.Key = QtWidgets.QLabel(self.centralwidget)
        self.Key.setGeometry(QtCore.QRect(160, 200, 31, 21))
        self.Key.setObjectName("Key")
        self.CipherText = QtWidgets.QLabel(self.centralwidget)
        self.CipherText.setGeometry(QtCore.QRect(160, 290, 91, 21))
        self.CipherText.setObjectName("CipherText")
        self.txtPlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPlainText.setGeometry(QtCore.QRect(260, 90, 381, 87))
        self.txtPlainText.setObjectName("txtPlainText")
        self.txtKey = QtWidgets.QTextEdit(self.centralwidget)
        self.txtKey.setGeometry(QtCore.QRect(260, 200, 381, 51))
        self.txtKey.setObjectName("txtKey")
        self.txtCipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txtCipherText.setGeometry(QtCore.QRect(260, 290, 381, 101))
        self.txtCipherText.setObjectName("txtCipherText")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(260, 420, 93, 28))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(450, 420, 93, 28))
        self.btnDecrypt.setMinimumSize(QtCore.QSize(93, 28))
        self.btnDecrypt.setObjectName("btnDecrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">CAESAR CIPHER</span></p></body></html>"))
        self.PlainText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">PlainText:</span></p></body></html>"))
        self.Key.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Key:</span></p></body></html>"))
        self.CipherText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">CipherText:</span></p></body></html>"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
